services:
  express-app:
    image: node:12-alpine
    container_name: server-dev
    working_dir: /usr/app
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command:
      - sh
      - -c
      - |
        npm install
        npm run dev
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    container_name: postgres-dev
    environment:
      POSTGRES_DB: atto_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./src/postgres/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis-dev
    volumes:
      - ./data/redis:/root/redis
    ports:
      - "6379:6379"
