services:
  express-app:
    image: node:12-alpine
    container_name: server-test
    working_dir: /usr/app
    volumes:
      - .:/usr/app/
    environment:
      - NODE_ENV=test
    command:
      - sh
      - -c
      - |
        npm install
        tail -f /dev/null
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    container_name: postgres-test
    environment:
      POSTGRES_DB: atto_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis-test
    ports:
      - "6379:6379"
