drop table if exists transactions;
drop table if exists customer_saved_service;
drop table if exists customer_device;
drop table if exists customer_card;
drop table if exists customer;
drop table if exists error;
drop table if exists service;
drop table if exists service_category;
drop table if exists merchant;