require('dotenv').config();

const PORT = process.env.PORT;
const POSTGRES_URL = process.env.POSTGRES_URL;
const POSTGRES_SSL = process.env.POSTGRES_SSL;
const REDIS_URL = process.env.REDIS_URL;
const REDIS_TLS = process.env.REDIS_TLS;
const NODE_ENV = process.env.NODE_ENV;

const AWS_BUCKET_NAME = process.env.AWS_BUCKET_NAME;
const AWS_BUCKET_REGION = process.env.AWS_BUCKET_REGION;
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const AWS_BUCKET_ENDPOINT = process.env.AWS_BUCKET_ENDPOINT;
const AWS_BUCKET_CDN_ENDPOINT = process.env.AWS_BUCKET_CDN_ENDPOINT;

const GMAIL_CLIENT_ID = process.env.GMAIL_CLIENT_ID;
const GMAIL_CLIENT_SECRET = process.env.GMAIL_CLIENT_SECRET;
const GMAIL_REFRESH_TOKEN = process.env.GMAIL_REFRESH_TOKEN;
const GMAIL_USER = process.env.GMAIL_USER;

const CRM_API_URL = process.env.CRM_API_URL;
const CRM_SMS_SERVICE_SECRET = process.env.CRM_SMS_SERVICE_SECRET;
const CRM_AGGREGATOR_NAME = process.env.CRM_AGGREGATOR_NAME;
const CRM_AGGREGATOR_SECRET = process.env.CRM_AGGREGATOR_SECRET;
const CRM_USER_LOGIN = process.env.CRM_USER_LOGIN;
const CRM_USER_PASSWORD = process.env.CRM_USER_PASSWORD;
const SV_GATE_URL = process.env.SV_GATE_URL;
const SV_GATE_USER = process.env.SV_GATE_USER;
const SV_GATE_PASSWORD = process.env.SV_GATE_PASSWORD;
const ATTO_FARE_SERVICE_ID = process.env.ATTO_FARE_SERVICE_ID;

module.exports = {
  PORT,
  POSTGRES_URL,
  POSTGRES_SSL,
  REDIS_URL,
  REDIS_TLS,
  NODE_ENV,
  AWS_BUCKET_NAME,
  AWS_BUCKET_REGION,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_ENDPOINT,
  AWS_BUCKET_CDN_ENDPOINT,
  GMAIL_CLIENT_ID,
  GMAIL_CLIENT_SECRET,
  GMAIL_REFRESH_TOKEN,
  GMAIL_USER,
  CRM_API_URL,
  CRM_SMS_SERVICE_SECRET,
  CRM_AGGREGATOR_NAME,
  CRM_AGGREGATOR_SECRET,
  CRM_USER_LOGIN,
  CRM_USER_PASSWORD,
  SV_GATE_URL,
  SV_GATE_USER,
  SV_GATE_PASSWORD,
  ATTO_FARE_SERVICE_ID,
};
