name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Digital Ocean Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Pull Latest Changes
        working-directory: /usr/src/projects/atto_project
        run: |
          git pull
          npm install

      - name: Restart PM2 Service
        run: pm2 restart atto-pay
